"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.signPsbtWithPrompt = exports.signPsbt = exports.isEnabled = exports.getPsbtPreview = exports.getInfo = exports.getAddressOrPrompt = exports.getAddress = exports.enable = void 0;
const enable_1 = __importDefault(require("~/extension/background-script/actions/webbtc/enable"));
exports.enable = enable_1.default;
const getAddress_1 = __importDefault(require("~/extension/background-script/actions/webbtc/getAddress"));
exports.getAddress = getAddress_1.default;
const getAddressOrPrompt_1 = __importDefault(require("~/extension/background-script/actions/webbtc/getAddressOrPrompt"));
exports.getAddressOrPrompt = getAddressOrPrompt_1.default;
const getInfo_1 = __importDefault(require("~/extension/background-script/actions/webbtc/getInfo"));
exports.getInfo = getInfo_1.default;
const getPsbtPreview_1 = __importDefault(require("~/extension/background-script/actions/webbtc/getPsbtPreview"));
exports.getPsbtPreview = getPsbtPreview_1.default;
const isEnabled_1 = __importDefault(require("~/extension/background-script/actions/webbtc/isEnabled"));
exports.isEnabled = isEnabled_1.default;
const signPsbt_1 = __importDefault(require("~/extension/background-script/actions/webbtc/signPsbt"));
exports.signPsbt = signPsbt_1.default;
const signPsbtWithPrompt_1 = __importDefault(require("~/extension/background-script/actions/webbtc/signPsbtWithPrompt"));
exports.signPsbtWithPrompt = signPsbtWithPrompt_1.default;
