"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventKind = void 0;
var EventKind;
(function (EventKind) {
    EventKind[EventKind["Metadata"] = 0] = "Metadata";
    EventKind[EventKind["Text"] = 1] = "Text";
    EventKind[EventKind["RelayRec"] = 2] = "RelayRec";
    EventKind[EventKind["Contacts"] = 3] = "Contacts";
    EventKind[EventKind["DM"] = 4] = "DM";
    EventKind[EventKind["Deleted"] = 5] = "Deleted";
    EventKind[EventKind["Repost"] = 6] = "Repost";
    EventKind[EventKind["React"] = 7] = "React";
    EventKind[EventKind["AwardBadge"] = 8] = "AwardBadge";
    EventKind[EventKind["CreateChannel"] = 40] = "CreateChannel";
    EventKind[EventKind["UpdateChannel"] = 41] = "UpdateChannel";
    EventKind[EventKind["SendChannelMessage"] = 42] = "SendChannelMessage";
    EventKind[EventKind["HideChannelMessage"] = 43] = "HideChannelMessage";
    EventKind[EventKind["MuteChannelUser"] = 44] = "MuteChannelUser";
    EventKind[EventKind["ReportNote"] = 1984] = "ReportNote";
    EventKind[EventKind["ZapRequest"] = 9734] = "ZapRequest";
    EventKind[EventKind["ZapReceipt"] = 9735] = "ZapReceipt";
    EventKind[EventKind["MuteList"] = 10000] = "MuteList";
    EventKind[EventKind["RelayList"] = 10002] = "RelayList";
    EventKind[EventKind["Bookmarks"] = 10003] = "Bookmarks";
    EventKind[EventKind["Authenticate"] = 22242] = "Authenticate";
    EventKind[EventKind["RemoteSign"] = 24133] = "RemoteSign";
    EventKind[EventKind["HTTPAuth"] = 27235] = "HTTPAuth";
    EventKind[EventKind["ProfileBadge"] = 30008] = "ProfileBadge";
    EventKind[EventKind["CreateBadge"] = 30009] = "CreateBadge";
    EventKind[EventKind["LongNote"] = 30023] = "LongNote";
    EventKind[EventKind["AppData"] = 30078] = "AppData";
    EventKind[EventKind["UploadChunk"] = 10000135] = "UploadChunk";
})(EventKind || (exports.EventKind = EventKind = {}));
