name: ✨ Feature request
description: Request a feature you'd like to see in lightning!
title: "[Feature] <title>"
labels: [idea]
body:
  - type: markdown
    attributes:
      value: |
        We're always looking for suggestions on how we could improve lightning!
  - type: textarea
    attributes:
      label: Feature description
      description: |
        Is your feature request related to a problem? A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives
      description: |
        A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other additional context or screenshots about the feature request here.
  - type: dropdown
    id: assign
    attributes:
      label: Are you working on this?
      options:
        - "Yes"
        - "No"
