"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const Container_1 = __importDefault(require("@components/Container"));
const Navbar_1 = __importDefault(require("@components/Navbar"));
const react_1 = require("@popicons/react");
const Accounts_1 = __importDefault(require("@screens/Accounts"));
const Detail_1 = __importDefault(require("@screens/Accounts/Detail"));
const ConfirmPayment_1 = __importDefault(require("@screens/ConfirmPayment"));
const DefaultView_1 = __importDefault(require("@screens/Home/DefaultView"));
const Keysend_1 = __importDefault(require("@screens/Keysend"));
const LNURLAuth_1 = __importDefault(require("@screens/LNURLAuth"));
const LNURLChannel_1 = __importDefault(require("@screens/LNURLChannel"));
const LNURLPay_1 = __importDefault(require("@screens/LNURLPay"));
const LNURLWithdraw_1 = __importDefault(require("@screens/LNURLWithdraw"));
const TestConnection_1 = __importDefault(require("@screens/Options/TestConnection"));
const Publishers_1 = __importDefault(require("@screens/Publishers"));
const Detail_2 = __importDefault(require("@screens/Publishers/Detail"));
const Receive_1 = __importDefault(require("@screens/Receive"));
const Send_1 = __importDefault(require("@screens/Send"));
const Settings_1 = __importDefault(require("@screens/Settings"));
const Transactions_1 = __importDefault(require("@screens/Transactions"));
const Unlock_1 = __importDefault(require("@screens/Unlock"));
const react_i18next_1 = require("react-i18next");
const react_router_dom_1 = require("react-router-dom");
const AccountDetailLayout_1 = __importDefault(require("~/app/components/AccountDetailLayout"));
const ScrollToTop_1 = __importDefault(require("~/app/components/ScrollToTop"));
const Toaster_1 = __importDefault(require("~/app/components/Toast/Toaster"));
const Providers_1 = __importDefault(require("~/app/context/Providers"));
const RequireAuth_1 = __importDefault(require("~/app/router/RequireAuth"));
const connectorRoutes_1 = require("~/app/router/connectorRoutes");
const BackupMnemonic_1 = __importDefault(require("~/app/screens/Accounts/BackupMnemonic"));
const GenerateMnemonic_1 = __importDefault(require("~/app/screens/Accounts/GenerateMnemonic"));
const new_1 = __importDefault(require("~/app/screens/Accounts/GenerateMnemonic/new"));
const ImportMnemonic_1 = __importDefault(require("~/app/screens/Accounts/ImportMnemonic"));
const NostrSettings_1 = __importDefault(require("~/app/screens/Accounts/NostrSettings"));
const LNURLRedeem_1 = __importDefault(require("~/app/screens/LNURLRedeem"));
const OnChainReceive_1 = __importDefault(require("~/app/screens/OnChainReceive"));
const ReceiveInvoice_1 = __importDefault(require("~/app/screens/ReceiveInvoice"));
const ScanQRCode_1 = __importDefault(require("~/app/screens/ScanQRCode"));
const SendToBitcoinAddress_1 = __importDefault(require("~/app/screens/SendToBitcoinAddress"));
const ChooseConnector_1 = __importDefault(require("~/app/screens/connectors/ChooseConnector"));
const ChooseConnectorPath_1 = __importDefault(require("~/app/screens/connectors/ChooseConnectorPath"));
const i18nConfig_1 = __importDefault(require("~/i18n/i18nConfig"));
function Options() {
    const connectorRoutes = (0, connectorRoutes_1.getConnectorRoutes)();
    return ((0, jsx_runtime_1.jsx)(Providers_1.default, { children: (0, jsx_runtime_1.jsxs)(react_router_dom_1.HashRouter, { children: [(0, jsx_runtime_1.jsx)(ScrollToTop_1.default, {}), (0, jsx_runtime_1.jsxs)(react_router_dom_1.Routes, { children: [(0, jsx_runtime_1.jsxs)(react_router_dom_1.Route, { path: "/", element: (0, jsx_runtime_1.jsx)(RequireAuth_1.default, { children: (0, jsx_runtime_1.jsx)(Layout, {}) }), children: [(0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { index: true, element: (0, jsx_runtime_1.jsx)(react_router_dom_1.Navigate, { to: "/wallet", replace: true }) }), (0, jsx_runtime_1.jsxs)(react_router_dom_1.Route, { path: "publishers", children: [(0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: ":id", element: (0, jsx_runtime_1.jsx)(Detail_2.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { index: true, element: (0, jsx_runtime_1.jsx)(Publishers_1.default, {}) })] }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "send", element: (0, jsx_runtime_1.jsx)(Send_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "confirmPayment", element: (0, jsx_runtime_1.jsx)(ConfirmPayment_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "keysend", element: (0, jsx_runtime_1.jsx)(Keysend_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "sendToBitcoinAddress", element: (0, jsx_runtime_1.jsx)(SendToBitcoinAddress_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "receive", element: (0, jsx_runtime_1.jsx)(Receive_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "receive/invoice", element: (0, jsx_runtime_1.jsx)(ReceiveInvoice_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "onChainReceive", element: (0, jsx_runtime_1.jsx)(OnChainReceive_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "wallet", element: (0, jsx_runtime_1.jsx)(DefaultView_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "transactions", element: (0, jsx_runtime_1.jsx)(Transactions_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "lnurlPay", element: (0, jsx_runtime_1.jsx)(LNURLPay_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "lnurlChannel", element: (0, jsx_runtime_1.jsx)(LNURLChannel_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "lnurlWithdraw", element: (0, jsx_runtime_1.jsx)(LNURLWithdraw_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "lnurlRedeem", element: (0, jsx_runtime_1.jsx)(LNURLRedeem_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "lnurlAuth", element: (0, jsx_runtime_1.jsx)(LNURLAuth_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "settings", element: (0, jsx_runtime_1.jsx)(Settings_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "scanQRCode", element: (0, jsx_runtime_1.jsx)(ScanQRCode_1.default, {}) }), (0, jsx_runtime_1.jsxs)(react_router_dom_1.Route, { path: "accounts", children: [(0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { index: true, element: (0, jsx_runtime_1.jsx)(Accounts_1.default, {}) }), (0, jsx_runtime_1.jsxs)(react_router_dom_1.Route, { path: ":id", element: (0, jsx_runtime_1.jsx)(AccountDetailLayout_1.default, {}), children: [(0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { index: true, element: (0, jsx_runtime_1.jsx)(Detail_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "secret-key/backup", element: (0, jsx_runtime_1.jsx)(BackupMnemonic_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "secret-key/generate", element: (0, jsx_runtime_1.jsx)(GenerateMnemonic_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "secret-key/new", element: (0, jsx_runtime_1.jsx)(new_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "secret-key/import", element: (0, jsx_runtime_1.jsx)(ImportMnemonic_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "nostr/settings", element: (0, jsx_runtime_1.jsx)(NostrSettings_1.default, {}) })] }), (0, jsx_runtime_1.jsxs)(react_router_dom_1.Route, { path: "new", element: (0, jsx_runtime_1.jsx)("div", { className: "flex flex-1 justify-center items-center", children: (0, jsx_runtime_1.jsx)(Container_1.default, { maxWidth: "xl", children: (0, jsx_runtime_1.jsx)(react_router_dom_1.Outlet, {}) }) }), children: [(0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { index: true, element: (0, jsx_runtime_1.jsx)(ChooseConnectorPath_1.default, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { index: true, element: (0, jsx_runtime_1.jsx)(ChooseConnectorPath_1.default, {}) }), (0, jsx_runtime_1.jsxs)(react_router_dom_1.Route, { path: "choose-connector", children: [(0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { index: true, element: (0, jsx_runtime_1.jsx)(ChooseConnector_1.default, { title: i18nConfig_1.default.t("translation:choose_connector.title"), description: i18nConfig_1.default.t("translation:choose_connector.description"), connectorRoutes: connectorRoutes }) }), (0, connectorRoutes_1.renderRoutes)(connectorRoutes)] })] })] }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "test-connection", element: (0, jsx_runtime_1.jsx)(Container_1.default, { children: (0, jsx_runtime_1.jsx)(TestConnection_1.default, {}) }) })] }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "unlock", element: (0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(Unlock_1.default, {}), (0, jsx_runtime_1.jsx)(Toaster_1.default, {})] }) })] })] }) }));
}
const Layout = () => {
    const { t: tCommon } = (0, react_i18next_1.useTranslation)("common");
    return ((0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col min-h-screen", children: [(0, jsx_runtime_1.jsxs)(Navbar_1.default, { children: [(0, jsx_runtime_1.jsx)(Navbar_1.default.Link, { href: "/wallet", children: tCommon("wallet") }), (0, jsx_runtime_1.jsx)(Navbar_1.default.Link, { href: "/publishers", children: tCommon("connected_sites") }), (0, jsx_runtime_1.jsxs)(Navbar_1.default.Link, { href: "https://getalby.com/discover", target: "_blank", children: [tCommon("discover"), (0, jsx_runtime_1.jsx)(react_1.PopiconsArrowUpLine, { className: "h-5 w-5 rotate-45" })] })] }), (0, jsx_runtime_1.jsx)(Toaster_1.default, {}), (0, jsx_runtime_1.jsx)(react_router_dom_1.Outlet, {})] }));
};
exports.default = Options;
