"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.signSchnorrOrPrompt = exports.signEventOrPrompt = exports.setPrivateKey = exports.removePrivateKey = exports.nip44EncryptOrPrompt = exports.nip44DecryptOrPrompt = exports.isEnabled = exports.getPublicKeyOrPrompt = exports.getPublicKey = exports.getPrivateKey = exports.generatePrivateKey = exports.encryptOrPrompt = exports.enable = exports.decryptOrPrompt = void 0;
const getPublicKey_1 = __importDefault(require("~/extension/background-script/actions/nostr/getPublicKey"));
exports.getPublicKey = getPublicKey_1.default;
const decryptOrPrompt_1 = __importDefault(require("./decryptOrPrompt"));
exports.decryptOrPrompt = decryptOrPrompt_1.default;
const enable_1 = __importDefault(require("./enable"));
exports.enable = enable_1.default;
const encryptOrPrompt_1 = __importDefault(require("./encryptOrPrompt"));
exports.encryptOrPrompt = encryptOrPrompt_1.default;
const generatePrivateKey_1 = __importDefault(require("./generatePrivateKey"));
exports.generatePrivateKey = generatePrivateKey_1.default;
const getPrivateKey_1 = __importDefault(require("./getPrivateKey"));
exports.getPrivateKey = getPrivateKey_1.default;
const getPublicKeyOrPrompt_1 = __importDefault(require("./getPublicKeyOrPrompt"));
exports.getPublicKeyOrPrompt = getPublicKeyOrPrompt_1.default;
const isEnabled_1 = __importDefault(require("./isEnabled"));
exports.isEnabled = isEnabled_1.default;
const nip44DecryptOrPrompt_1 = __importDefault(require("./nip44DecryptOrPrompt"));
exports.nip44DecryptOrPrompt = nip44DecryptOrPrompt_1.default;
const nip44EncryptOrPrompt_1 = __importDefault(require("./nip44EncryptOrPrompt"));
exports.nip44EncryptOrPrompt = nip44EncryptOrPrompt_1.default;
const removePrivateKey_1 = __importDefault(require("./removePrivateKey"));
exports.removePrivateKey = removePrivateKey_1.default;
const setPrivateKey_1 = __importDefault(require("./setPrivateKey"));
exports.setPrivateKey = setPrivateKey_1.default;
const signEventOrPrompt_1 = __importDefault(require("./signEventOrPrompt"));
exports.signEventOrPrompt = signEventOrPrompt_1.default;
const signSchnorrOrPrompt_1 = __importDefault(require("./signSchnorrOrPrompt"));
exports.signSchnorrOrPrompt = signSchnorrOrPrompt_1.default;
