name: Build PR previews

on: issue_comment

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    env:
      FAUCET_URL: ${{ secrets.FAUCET_URL }}
      FAUCET_K: ${{ secrets.FAUCET_K }}

    name: build-branch
        
    steps:
      - uses: actions/checkout@v2
      - name: checkout RR 
        uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ github.event.pull_request.number }}/merge'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - run: yarn install

      - name: Build production
        run: yarn build

      - name: Archive firefox production zip file
        uses: actions/upload-artifact@v2
        with:
          name: firefox.xpi
          path: dist/production/firefox.xpi

      - name: Archive chrome production zip file
        uses: actions/upload-artifact@v2
        with:
          name: chrome.zip
          path: dist/production/chrome.zip

      - name: Archive opera production zip file
        uses: actions/upload-artifact@v2
        with:
          name: opera.crx
          path: dist/production/opera.crx

  release-firefox-nightly:
    runs-on: ubuntu-latest
    needs: build
    
    env:
      FILE: 'firefox.xpi'
      AWS_REGION: 'eu-central-1'
      S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_KEY: "alby-firefox-nightly-master.xpi"

    name: release-firefox-nightly
    steps:
      - name: Download firefox.xpi
        uses: actions/download-artifact@v2
        with:
          name: firefox.xpi
      - name: Upload releases to S3
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read --content-type application/x-xpinstall

  release-chrome-nightly:
    runs-on: ubuntu-latest
    needs: build
    env:
      FILE: 'chrome.zip'
      AWS_REGION: 'eu-central-1'
      S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_KEY: "alby-chrome-nightly-master.zip"

    name: release-chrome-nightly
    steps:
      - name: Download chrome.zip
        uses: actions/download-artifact@v2
        with:
          name: chrome.zip
      - name: Upload releases to S3
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read

  release-opera-nightly:
    runs-on: ubuntu-latest
    needs: build
    env:
      FILE: 'opera.crx'
      AWS_REGION: 'eu-central-1'
      S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_KEY: "alby-opera-nightly-master.crx"

    name: release-opera-nightly
    steps:
      - name: Download opera.crz
        uses: actions/download-artifact@v2
        with:
          name: opera.crx
      - name: Upload releases to S3
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
