name: Storybook (build check only)

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  build-storybook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"

      - run: yarn install

      - name: Storybook build
        run: yarn build-storybook
